"""empty message

Revision ID: 92dc7a99e2dd
Revises: feff1766e938
Create Date: 2024-11-13 20:50:29.270240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92dc7a99e2dd'
down_revision = 'feff1766e938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_de_usuario', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('sexo', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('edad', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['nombre_de_usuario'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('edad')
        batch_op.drop_column('sexo')
        batch_op.drop_column('nombre')
        batch_op.drop_column('nombre_de_usuario')

    # ### end Alembic commands ###
